services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: hypesoft-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

  mongodb:
    image: mongo:7.0
    container_name: hypesoft-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: HypesoftDB
    volumes:
      - mongodb_data:/data/db

volumes:
  keycloak_data:
  mongodb_data:

